'use strict';
(async()=>{
 const $=s=>document.querySelector(s);let project,at=0,mode='book';
 function wrap(page,scale){const w=document.createElement('div');w.className='page-wrap';w.style.width=project.width*scale+'px';w.style.height=project.height*scale+'px';const sheet=TLWC.makePage(project,page,'reader');sheet.style.transform=`scale(${scale})`;w.append(sheet);return w;}
 function indices(){return innerWidth<650||at===0?[at]:[at,at+1].filter(i=>i<project.pages.length)}
 function render(){const main=$('#main');main.replaceChildren();$('#book').setAttribute('aria-pressed',mode==='book');$('#grid').setAttribute('aria-pressed',mode==='grid');$('#pages').value=at;
 if(mode==='grid'){const grid=document.createElement('div');grid.className='grid';main.append(grid);const columns=innerWidth<650?2:Math.max(2,Math.floor((innerWidth-36)/246));const s=Math.min(.6,(main.clientWidth-(columns-1)*26)/columns/project.width);project.pages.forEach((p,i)=>{const card=document.createElement('button');card.className='card';card.setAttribute('aria-label',`Apri pagina ${i+1}: ${p.name}`);card.append(wrap(p,s));const label=document.createElement('p');label.textContent=`${i+1} · ${p.name}`;card.append(label);card.onclick=()=>{at=i===0||innerWidth<650?i:(i%2?i:i-1);mode='book';render();scrollTo(0,0)};grid.append(card)});}else{const ids=indices(),spread=document.createElement('div');spread.className='spread';const s=Math.min(1.4,(innerWidth-40)/(project.width*ids.length),Math.max(360,innerHeight-220)/project.height);ids.forEach(i=>spread.append(wrap(project.pages[i],s)));main.append(spread);}
 $('#position').textContent=indices().map(i=>i+1).join('–')+' / '+project.pages.length;$('#prev').disabled=at===0;$('#next').disabled=indices().at(-1)>=project.pages.length-1;
 }
 try{const r=await fetch('edition.json');if(!r.ok)throw Error();project=await r.json();project.pages=project.pages.filter(p=>!p.hidden);if(!project.pages.length)throw Error();await TLWC.loadFonts(project);project.pages.forEach((p,i)=>{const op=document.createElement('option');op.value=i;op.textContent=`${i+1} · ${p.name}`;$('#pages').append(op)});$('#pages').onchange=()=>{const i=Number($('#pages').value);at=innerWidth<650||i===0?i:i%2?i:i-1;mode='book';render()};$('#prev').onclick=()=>{at=Math.max(0,at-(innerWidth<650?1:2));render()};$('#next').onclick=()=>{at=Math.min(project.pages.length-1,at+(innerWidth<650||at===0?1:2));render()};$('#book').onclick=()=>{mode='book';render()};$('#grid').onclick=()=>{mode='grid';render()};$('#share').onclick=async()=>{try{await navigator.clipboard.writeText(new URL('./',location.href).href);$('#share').textContent='Link copiato';setTimeout(()=>$('#share').textContent='Copia link',2200)}catch{prompt('Copia questo link',new URL('./',location.href).href)}};$('#pdf').onclick=async()=>{const b=$('#pdf');b.disabled=true;try{b.textContent='Preparazione PDF…';const pdfProject=structuredClone(project);await Promise.all(Object.values(pdfProject.assets).map(async a=>{const response=await fetch(a.src);if(!response.ok)throw Error('Immagine non disponibile');const blob=await response.blob();a.src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob)})}));await TLWCPdf.export(pdfProject,s=>b.textContent=s.message||`PDF ${s.percent}%`)}catch{alert('Download PDF non riuscito. Riprova tra poco.')}finally{b.disabled=false;b.textContent='Scarica PDF'}};addEventListener('resize',render);addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.key==='ArrowRight'&&!$('#next').disabled)$('#next').click();if(e.key==='ArrowLeft'&&!$('#prev').disabled)$('#prev').click()});render();
 }catch{$('#main').innerHTML='<p class="message">Il magazine non è disponibile in questo momento. Ricarica la pagina per riprovare.</p>';$('#pdf').disabled=true;}
})();
