'use strict';
window.TLWC = (()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const safeURL=(s,media=false)=>{s=String(s||'').trim();return /^(https?:|mailto:|tel:|#)/i.test(s)||(media&&/^data:(image|video|font)\//.test(s))?s:''};
 const sanitize=html=>{const t=document.createElement('template');t.innerHTML=html||'';function walk(root){[...root.childNodes].forEach(n=>{if(n.nodeType===1){if(!['B','STRONG','I','EM','U','BR','SPAN','P','A','DIV'].includes(n.tagName)){n.replaceWith(document.createTextNode(n.textContent));return;}const href=n.tagName==='A'?safeURL(n.getAttribute('href')):null;[...n.attributes].forEach(a=>n.removeAttribute(a.name));if(href){n.href=href;n.target='_blank';n.rel='noopener noreferrer'}walk(n)}})}walk(t.content);return t.innerHTML};
 const textHTML=t=>esc(t).replace(/\n/g,'<br>');
 const plain=h=>{const d=document.createElement('div');d.innerHTML=h.replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/p>|<\/div>/gi,'\n');return d.textContent||''};
 const blobCache=new WeakMap();
 function assetSrc(a){if(!a)return '';if(!a.src?.startsWith('data:'))return a.src||'';if(blobCache.has(a))return blobCache.get(a);const parts=a.src.split(','),binary=atob(parts[1]),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const url=URL.createObjectURL(new Blob([bytes],{type:parts[0].slice(5).split(';')[0]}));blobCache.set(a,url);return url;}
 let fontsReady;
 async function loadFonts(p){fontsReady=Promise.all(Object.entries(p.fonts||{}).map(async([alias,f])=>{const src=f.src||p.assets[f.assetId]?.src;if(!src)return;try{const ff=new FontFace(f.family||alias,`url("${src}")`,{weight:String(f.weight||400),style:f.style||'normal'});await ff.load();document.fonts.add(ff)}catch(e){console.warn('Font unavailable',alias)}}));await fontsReady;}
 const ctx=document.createElement('canvas').getContext('2d');const metrics=new Map();
 function typography(p,e){const f=p.fonts?.[e.fontFamily]||{};const size=Number(e.fontSize)||14,lh=Number(e.lineHeight)||size*1.2;const family=f.family||e.fontFamily||'Georgia';const weight=e.fontWeight&&e.fontWeight!=='normal'?e.fontWeight:(f.weight||400),style=e.fontStyle&&e.fontStyle!=='normal'?e.fontStyle:(f.style||'normal');const key=[family,weight,style,size,lh].join('/');let baseline=metrics.get(key);if(baseline===undefined){ctx.font=`${style} ${weight} ${size}px "${family}"`;const m=ctx.measureText('Hg');baseline=(lh-(m.fontBoundingBoxAscent||size*.8)-(m.fontBoundingBoxDescent||size*.2))/2+(m.fontBoundingBoxAscent||size*.8);metrics.set(key,baseline)}return {family,size,lh,weight,style,baseline};}
 function fragment(p,f){const font=p.fonts?.[f.fontFamily]||{};let s=`<span style="font-family:${esc(font.family||f.fontFamily||'inherit')};font-weight:${font.weight||400};font-style:${font.style||'normal'};color:${esc(f.color||'inherit')}">${esc(f.text)}</span>`;for(const l of f.links||[]){const u=safeURL(typeof l==='string'?l:l.href||l.url||'');if(u)s=`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${s}</a>`}return s;}
 function imgStyle(p,e,img){const a=p.assets[e.assetId];if(!a)return;const iw=a.width||e.w,ih=a.height||e.h,c=e.fit==='cover'&&e.crop?e.crop:{x:0,y:0,w:1,h:1};const cw=iw*c.w,ch=ih*c.h;const s=e.fit==='cover'?Math.max(e.w/cw,e.h/ch):Math.min(e.w/cw,e.h/ch);Object.assign(img.style,{position:'absolute',width:iw*s+'px',height:ih*s+'px',maxWidth:'none',left:((e.w-cw*s)*(e.positionX??.5)-c.x*iw*s)+'px',top:((e.h-ch*s)*(e.positionY??.5)-c.y*ih*s)+'px',clipPath:`inset(${c.y*ih*s}px ${(1-c.x-c.w)*iw*s}px ${(1-c.y-c.h)*ih*s}px ${c.x*iw*s}px)`});}
 function videoURL(e){let s=safeURL(e.src,true);try{const u=new URL(s);if(/(?:^|\.)youtube\.com$/.test(u.hostname)||u.hostname==='youtu.be'){const id=u.hostname==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.split('/').pop();return {kind:'embed',src:`https://www.youtube-nocookie.com/embed/${encodeURIComponent(id)}?rel=0`}}if(/(?:^|\.)vimeo\.com$/.test(u.hostname)){const id=u.pathname.split('/').filter(Boolean).pop();if(/^\d+$/.test(id))return {kind:'embed',src:'https://player.vimeo.com/video/'+id}}}catch{}return {kind:'file',src:s};}
 function makeElement(p,e,mode='editor'){
 const radius=e.frameShape==='ellipse'?'50%':(e.borderRadius||0)+'px';const el=document.createElement('div');el.className=`el ${e.type} effect-${e.effect||'none'}`;el.dataset.id=e.id;el.dataset.editor=String(mode==='editor');
 Object.assign(el.style,{left:e.x+'px',top:e.y+'px',width:Math.max(.1,e.w)+'px',height:Math.max(.1,e.h)+'px',transform:`rotate(${e.rotation||0}deg)`,opacity:e.opacity??1,zIndex:e.z||0,display:e.hidden?'none':'',borderRadius:radius});
 if(e.locked)el.classList.add('locked');const fx=document.createElement('div');fx.className='fx';el.append(fx);
 if(e.type==='text'){
 const t=typography(p,e);const inner=document.createElement('div');inner.className='text-inner';Object.assign(inner.style,{fontFamily:`"${t.family}",Georgia,serif`,fontSize:t.size+'px',lineHeight:t.lh+'px',fontWeight:t.weight,fontStyle:t.style,letterSpacing:(e.letterSpacing||0)+'px',color:e.color||'#101318',textAlign:e.textAlign||'left',whiteSpace:e.singleLine?'nowrap':'normal',fontKerning:'none',fontVariantLigatures:'none',transform:`translateY(${(e.baselineOffset??t.baseline)-t.baseline}px)`});
 if(e.sourceLines?.length){inner.innerHTML=e.sourceLines.map(line=>`<div class="source-line" style="height:${t.lh}px;white-space:nowrap">${line.fragments?.length?line.fragments.map(f=>fragment(p,f)).join(''):esc(line.text)}</div>`).join('');}else inner.innerHTML=sanitize(e.html??textHTML(e.text||''));fx.append(inner);
 }else if(e.type==='image'){
 fx.style.cssText=`position:relative;overflow:hidden;width:100%;height:100%;border-radius:${radius};box-sizing:border-box;border:${e.borderWidth||0}px solid ${e.borderColor||'transparent'}`;if(e.isFrame&&!p.assets[e.assetId]){fx.style.background='#e5eff4';const hint=document.createElement('div');hint.style.cssText='height:100%;display:grid;place-items:center;text-align:center;font:14px Arial;color:#36546b';hint.textContent='＋ Foto / video';fx.append(hint)}else{const img=document.createElement('img');img.src=assetSrc(p.assets[e.assetId]);img.alt=e.alt||p.assets[e.assetId]?.subject||p.assets[e.assetId]?.name||'';img.draggable=false;imgStyle(p,e,img);fx.append(img);}
 }else if(e.type==='shape')Object.assign(fx.style,{width:'100%',height:'100%',background:e.fill||'transparent',borderRadius:e.shape==='ellipse'?'50%':(e.borderRadius||0)+'px',border:`${e.borderWidth||0}px solid ${e.borderColor||'transparent'}`,boxSizing:'border-box'});
 else if(e.type==='line'){const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('width','100%');s.setAttribute('height','100%');s.setAttribute('viewBox',`0 0 ${Math.max(e.w,1)} ${Math.max(e.h,1)}`);s.style.overflow='visible';s.innerHTML=`<line x1="0" y1="0" x2="${Math.max(e.w,0)}" y2="${e.h||0}" stroke="${esc(e.color||'#101318')}" stroke-width="${e.lineWidth||1}"/>`;fx.append(s)}
 else if(e.type==='video'){
 fx.style.cssText=`width:100%;height:100%;background:#101318;overflow:hidden;position:relative;border-radius:${radius};box-sizing:border-box;border:${e.borderWidth||0}px solid ${e.borderColor||'transparent'}`;if(mode==='editor'){const a=p.assets[e.posterAssetId];if(a){const img=new Image();img.src=assetSrc(a);img.style.cssText='width:100%;height:100%;object-fit:cover';fx.append(img)}const label=document.createElement('div');label.className='video-placeholder';label.textContent='▶ VIDEO';fx.append(label)}else{const v=videoURL(e);if(v.kind==='embed'){const iframe=document.createElement('iframe');iframe.src=v.src;iframe.title=e.title||'Video';iframe.allow='fullscreen; picture-in-picture';iframe.allowFullscreen=true;iframe.style.cssText='width:100%;height:100%;border:0';fx.append(iframe)}else if(v.src){const video=document.createElement('video');video.src=v.src;video.poster=assetSrc(p.assets[e.posterAssetId]);video.controls=e.controls!==false;video.loop=!!e.loop;video.muted=!!e.muted;video.autoplay=!!e.autoplay&&video.muted;video.playsInline=true;video.style.cssText=`width:100%;height:100%;object-fit:${e.fit==='cover'?'cover':'contain'}`;fx.append(video)}else fx.innerHTML='<div class="video-placeholder">Video</div>'}}
 if(mode!=='editor'&&safeURL(e.link)&&e.type!=='video'){const a=document.createElement('a');a.href=safeURL(e.link);a.target='_blank';a.rel='noopener noreferrer';a.title=e.link;a.style.cssText='position:absolute;inset:0;z-index:20';a.setAttribute('aria-label',e.text||e.alt||'Open link');el.append(a)}
 return el;
 }
 function makePage(p,page,mode='editor'){const sh=document.createElement('div');sh.className='sheet '+(mode==='editor'?'':'reader fx-active');sh.dataset.page=page.id;sh.style.width=p.width+'px';sh.style.height=p.height+'px';sh.style.background=page.backgroundGradient||page.background||'#fff';if(page.backgroundImageId&&p.assets[page.backgroundImageId]){const bg=makeElement(p,{id:'page-background-'+page.id,type:'image',x:0,y:0,w:p.width,h:p.height,assetId:page.backgroundImageId,fit:page.backgroundFit||'contain',positionX:page.backgroundPositionX??.5,positionY:page.backgroundPositionY??.5,crop:page.backgroundCrop,opacity:1},mode);bg.className='page-background';bg.style.position='absolute';bg.style.zIndex='-1';bg.style.pointerEvents='none';sh.append(bg)}page.elements.forEach(e=>sh.append(makeElement(p,e,mode)));return sh;}
 function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
 function json(p){return JSON.stringify(p).replace(/</g,'\\u003c')}
 function moduleText(id){return document.getElementById(id)?.textContent||''}
 function readerProject(p){const result={...p,pages:(p.pages||[]).filter(pg=>pg.hidden!==true)};delete result.editorHistory;const used=new Set();for(const pg of result.pages){if(pg.backgroundImageId)used.add(pg.backgroundImageId);for(const e of pg.elements||[]){if(e.assetId)used.add(e.assetId);if(e.posterAssetId)used.add(e.posterAssetId)}}for(const f of Object.values(result.fonts||{}))if(f.assetId)used.add(f.assetId);result.assets=Object.fromEntries(Object.entries(p.assets||{}).filter(([id])=>used.has(id)));return result;}
 function readerHTML(p){p=readerProject(p);if(!p.pages.length)throw new Error('No published pages. Make at least one draft page visible before exporting.');return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>'+esc(p.title)+'</title><style>'+moduleText('editor-css')+moduleText('reader-css')+'</style></head><body class="reader-body"><div id="reader-root"></div><script id="project-data" type="application/json">'+json(p)+'</script><script>'+moduleText('pdf-lib')+'</script><script>'+moduleText('pdf-export')+'</script><script>'+moduleText('runtime')+'</script><script>TLWC.startReader(JSON.parse(document.getElementById("project-data").textContent));<\/script></body></html>'}
 async function startReader(p){p=readerProject(p);document.title=p.title;const root=document.getElementById('reader-root');if(!p.pages.length){root.innerHTML='<main class="reader-main" style="padding:48px 24px;text-align:center"><h1>No published pages yet</h1><p>All pages are saved as drafts. Make a page visible in the editor to publish it.</p></main>';return;}await loadFonts(p);root.innerHTML='<nav class="reader-nav"><strong>'+esc(p.title)+'</strong><select aria-label="Go to page">'+p.pages.map((pg,i)=>`<option value="${pg.id}">${i+1} · ${esc(pg.name)}</option>`).join('')+'</select><button id="reader-pdf">Download PDF</button></nav><main class="reader-main"></main>';const main=root.querySelector('main');p.pages.forEach(pg=>{const wrap=document.createElement('div');wrap.className='reader-wrap';wrap.id=pg.id;wrap.append(makePage(p,pg,'reader'));main.append(wrap)});function resize(){main.querySelectorAll('.reader-wrap').forEach(w=>{const s=Math.min(1.4,(window.innerWidth-32)/p.width);w.style.width=p.width*s+'px';w.style.height=p.height*s+'px';w.firstChild.style.transform=`scale(${s})`})}resize();addEventListener('resize',resize);root.querySelector('select').onchange=e=>document.getElementById(e.target.value).scrollIntoView({behavior:'smooth'});root.querySelector('#reader-pdf').onclick=async e=>{e.target.disabled=true;try{await TLWCPdf.export(p,s=>e.target.textContent=s.message||`PDF ${s.percent}%`)}catch(err){alert('PDF export: '+err.message)}finally{e.target.disabled=false;e.target.textContent='Download PDF'}};}
 return {esc,safeURL,sanitize,textHTML,plain,loadFonts,typography,makeElement,makePage,download,json,readerHTML,startReader};
})();
